RndBoxAuthBundle_home:
    pattern: /auth/home/
    defaults: { _controller: RndBoxAuthBundle:default:index }



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
